# game_config.yaml
countdown:
  time_seconds: 63
  display:
    pid: 0x01
    ports:
      serial_out:
        type: output
        mode: display

slider_module:
  name: "Slider"
  devices:
    - pid: 0x801f
      ports:
        slider1: # bottom, doesn't work
          type: input
          range: [2, 3]  # must set to this value
        slider2:
          type: input
          range: [3, 5]  # set [0,1] for 1, [1,2] for 2, [2,3] for 3, [3,4] for 4, [4,5] for 5

four_wires_module:
  name: "4-wires"
  devices:
    - pid: 0x801f
      ports:
        green:
          type: input
          target_state: 1
        # red:
        #   type: input
        #   # red doesn't work, always set to 0
        #   target_state: 0
        white:
          type: input
          target_state: 1
        black:
          type: input
          target_state: 1

four_buttons_module:
  name: "4-buttons"
  devices:
    - pid: 0x801f
      ports:
        red:
          type: input 
          target_state: 1 # set to 1 for pressed
        green:
          type: input
          target_state: 0
        blue:
          type: input
          target_state: 0
        white:
          type: input
          target_state: 0

rotary_module:
  name: "Direction Encoder"
  devices:
    - pid: 0x80fc
      ports:
        rotary:
          type: input
          range: [4.5, 5.5]  # 

gpio_module:
  name: "Switches and LEDs"
  devices:
    - pid: 0x800
      ports:
        switch_input_1: # left
          type: input
          pin: 0
          target_state: True  # True for on, False for off
        switch_input_2: # right
          type: input
          pin: 1
          target_state: False # True for on, False for off
        led_output_1:
          type: output
          pin: 2
          initial_state: 0  # LED starts on or off
        led_output_2:
          type: output
          pin: 3
          initial_state: 0
        led_output_3:
          type: output
          pin: 4
          initial_state: 0