import os

DATA_DIR = os.path.expanduser('~/aloha_data')
COLLECTION_CONFIG = {
    'dataset_dir': DATA_DIR + '/busybox_collection',
    'camera_names': ['cam_high', 'cam_left_wrist', 'cam_right_wrist'],
    'using_instrumented_busybox': True,  # requires BusyBox to publish to MQTT
    'MQTT_broker': 'localhost',
    'MQTT_port': 1883,
}

MQTT_TOPICS = {
    'buttons': 'busybox/buttons/state',
    'knob': 'busybox/knob/state',
    'sliders': 'busybox/sliders/state',
    'switches': 'busybox/switches/state',
    'wires': 'busybox/wires/state',
}

TASKBOX_TASKS = {
    # PullWire instructions
    1: ("PullWire", "Pull the red wire with the left gripper."),
    2: ("PullWire", "Pull the red wire with the right gripper."),
    3: ("PullWire", "Pull the blue wire with the left gripper."),
    4: ("PullWire", "Pull the blue wire with the right gripper."),
    5: ("PullWire", "Pull the black wire with the left gripper."),
    6: ("PullWire", "Pull the black wire with the right gripper."),
    7: ("PullWire", "Pull the white wire with the left gripper."),
    8: ("PullWire", "Pull the white wire with the right gripper."),
    9: ("PullWire", "Pull wire 1 with the left gripper."),
    10: ("PullWire", "Pull wire 1 with the right gripper."),
    11: ("PullWire", "Pull wire 2 with the left gripper."),
    12: ("PullWire", "Pull wire 2 with the right gripper."),
    13: ("PullWire", "Pull wire 3 with the left gripper."),
    14: ("PullWire", "Pull wire 3 with the right gripper."),
    15: ("PullWire", "Pull wire 4 with the left gripper."),
    16: ("PullWire", "Pull wire 4 with the right gripper."),

    # InsertWire instructions
    17: ("InsertWire", "Insert the red wire with the left gripper."),
    18: ("InsertWire", "Insert the red wire with the right gripper."),
    19: ("InsertWire", "Insert the blue wire with the left gripper."),
    20: ("InsertWire", "Insert the blue wire with the right gripper."),
    21: ("InsertWire", "Insert the black wire with the left gripper."),
    22: ("InsertWire", "Insert the black wire with the right gripper."),
    23: ("InsertWire", "Insert the white wire with the left gripper."),
    24: ("InsertWire", "Insert the white wire with the right gripper."),
    25: ("InsertWire", "Insert wire 1 with the left gripper."),
    26: ("InsertWire", "Insert wire 1 with the right gripper."),
    27: ("InsertWire", "Insert wire 2 with the left gripper."),
    28: ("InsertWire", "Insert wire 2 with the right gripper."),
    29: ("InsertWire", "Insert wire 3 with the left gripper."),
    30: ("InsertWire", "Insert wire 3 with the right gripper."),
    31: ("InsertWire", "Insert wire 4 with the left gripper."),
    32: ("InsertWire", "Insert wire 4 with the right gripper."),

    # PushButton instructions
    33: ("PushButton", "Push the white button with the left gripper."),
    34: ("PushButton", "Push the white button with the right gripper."),
    35: ("PushButton", "Push the yellow button with the left gripper."),
    36: ("PushButton", "Push the yellow button with the right gripper."),
    37: ("PushButton", "Push the green button with the left gripper."),
    38: ("PushButton", "Push the green button with the right gripper."),
    39: ("PushButton", "Push the red button with the left gripper."),
    40: ("PushButton", "Push the red button with the right gripper."),
    41: ("PushButton", "Push the top button with the left gripper."),
    42: ("PushButton", "Push the top button with the right gripper."),
    43: ("PushButton", "Push the bottom button with the left gripper."),
    44: ("PushButton", "Push the bottom button with the right gripper."),
    45: ("PushButton", "Push the left button with the left gripper."),
    46: ("PushButton", "Push the left button with the right gripper."),
    47: ("PushButton", "Push the right button with the left gripper."),
    48: ("PushButton", "Push the right button with the right gripper."),

    # MoveSlider instructions
    49: ("MoveSlider", "Move the top slider to position 1 with the left gripper."),
    50: ("MoveSlider", "Move the top slider to position 1 with the right gripper."),
    51: ("MoveSlider", "Move the top slider to position 2 with the left gripper."),
    52: ("MoveSlider", "Move the top slider to position 2 with the right gripper."),
    53: ("MoveSlider", "Move the top slider to position 3 with the left gripper."),
    54: ("MoveSlider", "Move the top slider to position 3 with the right gripper."),
    55: ("MoveSlider", "Move the top slider to position 4 with the left gripper."),
    56: ("MoveSlider", "Move the top slider to position 4 with the right gripper."),
    57: ("MoveSlider", "Move the top slider to position 5 with the left gripper."),
    58: ("MoveSlider", "Move the top slider to position 5 with the right gripper."),
    59: ("MoveSlider", "Move the bottom slider to position 1 with the left gripper."),
    60: ("MoveSlider", "Move the bottom slider to position 1 with the right gripper."),
    61: ("MoveSlider", "Move the bottom slider to position 2 with the left gripper."),
    62: ("MoveSlider", "Move the bottom slider to position 2 with the right gripper."),
    63: ("MoveSlider", "Move the bottom slider to position 3 with the left gripper."),
    64: ("MoveSlider", "Move the bottom slider to position 3 with the right gripper."),
    65: ("MoveSlider", "Move the bottom slider to position 4 with the left gripper."),
    66: ("MoveSlider", "Move the bottom slider to position 4 with the right gripper."),
    67: ("MoveSlider", "Move the bottom slider to position 5 with the left gripper."),
    68: ("MoveSlider", "Move the bottom slider to position 5 with the right gripper."),

    # TurnKnob instructions
    69: ("TurnKnob", "Turn the knob to position 1 with the left gripper."),
    70: ("TurnKnob", "Turn the knob to position 1 with the right gripper."),
    71: ("TurnKnob", "Turn the knob to position 2 with the left gripper."),
    72: ("TurnKnob", "Turn the knob to position 2 with the right gripper."),
    73: ("TurnKnob", "Turn the knob to position 3 with the left gripper."),
    74: ("TurnKnob", "Turn the knob to position 3 with the right gripper."),
    75: ("TurnKnob", "Turn the knob to position 4 with the left gripper."),
    76: ("TurnKnob", "Turn the knob to position 4 with the right gripper."),
    77: ("TurnKnob", "Turn the knob to position 5 with the left gripper."),
    78: ("TurnKnob", "Turn the knob to position 5 with the right gripper."),
    79: ("TurnKnob", "Turn the knob to position 6 with the left gripper."),
    80: ("TurnKnob", "Turn the knob to position 6 with the right gripper."),
    81: ("TurnKnob", "Turn the knob to point up with the left gripper."),
    82: ("TurnKnob", "Turn the knob to point up with the right gripper."),
    83: ("TurnKnob", "Turn the knob to point down with the left gripper."),
    84: ("TurnKnob", "Turn the knob to point down with the right gripper."),
    85: ("TurnKnob", "Turn the knob to point left with the left gripper."),
    86: ("TurnKnob", "Turn the knob to point left with the right gripper."),
    87: ("TurnKnob", "Turn the knob to point right with the left gripper."),
    88: ("TurnKnob", "Turn the knob to point right with the right gripper."),

    # Flip Switch instructions
    89: ("FlipSwitch", "Flip the left switch on with the left gripper."),
    90: ("FlipSwitch", "Flip the left switch on with the right gripper."),
    91: ("FlipSwitch", "Flip the left switch off with the left gripper."),
    92: ("FlipSwitch", "Flip the left switch off with the right gripper."),
    93: ("FlipSwitch", "Flip the right switch on with the left gripper."),
    94: ("FlipSwitch", "Flip the right switch on with the right gripper."),
    95: ("FlipSwitch", "Flip the right switch off with the left gripper."),
    96: ("FlipSwitch", "Flip the right switch off with the right gripper."),

    # Go to position instructions
    97: ("Reposition", "Return to the home position."),
    98: ("Reposition", "View the box from the top."),
    99: ("Reposition", "Open left gripper."),
    100: ("Reposition", "Open right gripper."),
    101: ("Reposition", "Open both grippers."),
    102: ("Reposition", "Close left gripper."),
    103: ("Reposition", "Close right gripper."),
    104: ("Reposition", "Close both grippers."),
    105: ("Reposition", "Move the left gripper to the left."),
    106: ("Reposition", "Move the left gripper to the right."),
    107: ("Reposition", "Move the right gripper to the left."),
    108: ("Reposition", "Move the right gripper to the right."),

    # Move box instructions
    109: ("MoveBox", "Move the box to the left."),
    110: ("MoveBox", "Move the box to the right."),
    111: ("MoveBox", "Move the box away."),
    112: ("MoveBox", "Move the box closer."),
    113: ("MoveBox", "Rotate the box clockwise."),
    114: ("MoveBox", "Rotate the box counterclockwise."),
}
